baseurl = "/"
languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"

title = "Rapyuta IO Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
# Enable Google Analytics by entering your tracking id
#googleAnalytics = ""

[params]
	# General information
	author = "Rapyuta IO"
	description = "Making robots more accessible to enterprise-level customers"
	copyright = ""

	# Repository
#	provider = "GitHub"
#	repo_url = "https://github.com/rapyuta-robotics"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Source Sans Pro"
    	code = "Source Code Pro"


[social]
	twitter = ""
	github  = ""
	email   = ""

#[[menu.main]]
#    identifier = "home"
#	name   = "Rapyuta IO Documentation"
#	url    = "/"
#	weight = "10"
[[menu.main]]
    identifier = "core-concepts"
	name   = "Core concepts"
	url    = "/core-concepts/"
	weight = "1"

[[menu.main]]
	identifier = "resource-user-group"
	parent = "core-concepts"
	name = "Resources, users and groups"
	url = "/core-concepts/resource-user-group/"
	weight = "2"

[[menu.main]]
	identifier = "create-new-group"
	parent = "core-concepts"
	name = "Creating a new group"
	url = "/core-concepts/create-new-group/"
	weight = "3"

[[menu.main]]
	identifier = "switch-between-user-group"
	parent = "core-concepts"
	name = "Switching between user and group"
	url = "/core-concepts/switch-between-user-group/"
	weight = "4"

[[menu.main]]
	identifier = "organisation"
	parent = "core-concepts"
	name = "Organisation"
	url = "/core-concepts/organisation/"
	weight = "5"

[[menu.main]]
	identifier = "packages"
	parent = "core-concepts"
	name = "Packages"
	url = "/core-concepts/packages"
	weight = "6"

[[menu.main]]
	identifier = "catalog"
	parent = "core-concepts"
	name = "Catalog"
	url = "/core-concepts/catalog"
	weight = "7"

[[menu.main]]
	identifier = "builds"
	parent = "core-concepts"
	name = "Builds"
	url = "/core-concepts/builds/"
	weight = "8"

[[menu.main]]
	identifier = "dockerfile-build-strategy"
	parent = "core-concepts"
	name = "Dockerfile build strategy"
	url = "/core-concepts/dockerfile-build-strategy/"
	weight = "9"

[[menu.main]]
	identifier = "secrets"
	parent = "core-concepts"
	name = "Secrets"
	url = "/core-concepts/secrets/"
	weight = "10"

[[menu.main]]
	identifier = "docker-pull-secret"
	parent = "core-concepts"
	name = "Docker pull secret"
	url = "/core-concepts/docker-pull-secret/"
	weight = "11"

[[menu.main]]
	identifier = "auth-token-docker-creds"
	parent = "core-concepts"
	name = "Authorisation token for docker credentials"
	url = "/core-concepts/auth-token-docker-creds/"
	weight = "12"

[[menu.main]]
	identifier = "source-secret"
	parent = "core-concepts"
	name = "Source secret"
	url = "/core-concepts/source-secret/"
	weight = "13"

[[menu.main]]
	identifier = "deployments"
	parent = "core-concepts"
	name = "Deployments"
	url = "/core-concepts/deployments/"
	weight = "14"

[[menu.main]]
	identifier = "persistent-volume-storage"
	parent = "core-concepts"
	name = "Persistent volume/storage"
	url = "/core-concepts/persistent-volume-storage/"
	weight = "15"

[[menu.main]]
	identifier = "logging-introduction"
	parent = "core-concepts"
	name = "Introduction to logging"
	url = "/core-concepts/logging-introduction/"
	weight = "16"

[[menu.main]]
	identifier = "build-logs"
	parent = "core-concepts"
	name = "Build logs"
	url = "/core-concepts/build-logs/"
	weight = "17"

[[menu.main]]
	identifier = "deployment-logs"
	parent = "core-concepts"
	name = "Deployment logs"
	url = "/core-concepts/deployment-logs/"
	weight = "18"

[[menu.main]]
	identifier = "device-logs"
	parent = "core-concepts"
	name = "Device logs"
	url = "/core-concepts/device-logs/"
	weight = "19"

[[menu.main]]
    identifier = "getting-started"
	name   = "Getting started"
	url    = "/getting-started/"
	weight = "20"

[[menu.main]]
	identifier = "create-new-user"
	parent = "getting-started"
	name   = "Creating a new user"
	url    = "/getting-started/create-new-user/"
	weight = "21"

[[menu.main]]
    identifier = "adding-a-new-device"
    parent = "getting-started"
	name   = "Adding A New Device"
	url    = "/getting-started/adding-a-new-device/"
	weight = "22"

[[menu.main]]
	identifier = "prepare-raspberry-pi"
	parent = "getting-started"
	name = "Preparing Raspberry PI"
	url = "/getting-started/prepare-raspberry-pi/"
	weight = "23"

[[menu.main]]
	identifier = "prepare-up-board"
	parent = "getting-started"
	name = "Preparing UP Board"
	url = "/getting-started/prepare-up-board"
	weight = "24"

[[menu.main]]
    identifier = "creating-a-new-package"
    parent = "getting-started"
	name   = "Creating a New Package"
	url    = "/getting-started/creating-a-new-package/"
	weight = "25"

[[menu.main]]
	identifier = "deploy-package"
	parent = "getting-started"
	name   = "Deploying a Package"
	url    = "/getting-started/deploy-package/"
	weight = "26"

[[menu.main]]
	identifier = "how-to-webssh"
	parent = "getting-started"
	name = "How to WebSSH"
	url = "/getting-started/how-to-webssh/"
	weight = "27"

[[menu.main]]
	identifier = "dev-tutorials"
	name = "Developer tutorials"
	url = "/dev-tutorials/"
	weight = "30"

[[menu.main]]
	identifier = "ros-pub-sub"
	parent = "dev-tutorials"
	name = "ROS publisher subscriber"
	url = "/dev-tutorials/ros-publisher-subscriber/"
	weight = "31"

[[menu.main]]
	identifier = "docker-pub-sub"
	parent = "dev-tutorials"
	name = "Docker publisher subscriber"
	url = "/dev-tutorials/docker-publisher-subscriber/"
	weight = "32"

[[menu.main]]
	identifier = "dynamic-map-server"
	parent = "dev-tutorials"
	name = "Dynamic map server"
	url = "/dev-tutorials/dynamic-map-server/"
	weight = "33"

[[menu.main]]
	identifier = "turtlesim"
	parent = "dev-tutorials"
	name = "Turtlesim"
	url = "dev-tutorials/turtlesim/"
	weight = "34"

[[menu.main]]
	identifier = "python-sdk"
	name = "rapyuta_io Python SDK"
	url = "/python-sdk/"
	weight = "40"

[[menu.main]]
	identifier = "sdk-introduction"
	parent = "python-sdk"
	name = "Overview of rapyuta_io Python SDK"
	url = "/python-sdk/introduction/"
	weight = "41"

[[menu.main]]
	identifier = "talker-listener-sdk"
	parent = "python-sdk"
	name = "Talker listener"
	url = "/python-sdk/talker-listener/"
	weight = "42"

[[menu.main]]
	identifier = "persistent-vol-sdk"
	parent = "python-sdk"
	name = "Persistent volume"
	url = "/python-sdk/persistent-volume/"
	weight = "43"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
