baseurl = "/"
languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"

title = "Rapyuta IO Documentation"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
#metadataformat = "yaml"
# Enable Google Analytics by entering your tracking id
#googleAnalytics = ""

[params]
    themeVariant = "rr"
	# General information
	author = "Rapyuta IO"
	description = "Making robots more accessible to enterprise-level customers"
	copyright = ""

	# Repository
#	provider = "GitHub"
#	repo_url = "https://github.com/rapyuta-robotics"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Source Sans Pro"
    	code = "Source Code Pro"


[social]
	twitter = ""
	github  = ""
	email   = ""

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
