baseurl = "/"
languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true

title = "rapyuta.io Documentation"
theme = "hugo-theme-learn"
disableSearch = false

[sitemap]
    changefreq = "monthly"
    priority = 1

[params]
    themeVariant = "rio"
    author = "Rapyuta Robotics"
    description = "Making robots more accessible to enterprise-level customers"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]


[outputs]
    home = ["HTML", "RSS", "JSON", "Algolia"]

[[menu.shortcuts]]
    name = "<i class='fas fa-atlas'></i> API Documentation"
    url = "https://gadocs.apps.rapyuta.io"
    weight = 9

[[menu.shortcuts]]
    name = "<i class='fas fa-atlas'></i> SDK Reference"
    url = "https://sdkdocs.apps.rapyuta.io/"
    weight = 10

[[menu.shortcuts]]
    identifier = "freshdesk"
    name = "<i class='fas fa-envelope'></i> Contact support"
    weight = 11

[[menu.shortcuts]]
    name = "<i class='fas fa-globe'></i> Rapyuta Robotics"
    url = "https://www.rapyuta-robotics.com/"
    weight = 12


