baseurl = "/"
languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"

title = "Rapyuta IO Documentation"
theme = "learn"
disableSearch = false

[params]
    themeVariant = "rio"
    author = "Rapyuta IO"
    description = "Making robots more accessible to enterprise-level customers"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[[menu.shortcuts]]
    name = "<i class='fas fa-globe'></i> Rapyuta Robotics"
    url = "https://www.rapyuta-robotics.com/"
    weight = 10

