= Deployments

A Deployment is a running instance of a package on the platform. A deployment can be triggered from the rapyuta.io console UI, RIO SDK or directly using 
REST API endpoints. While deploying a package the platform is responsible for:

* Resolving all specified package dependencies for a package. 
* Ensuring availability of all required catalog dependencies and then initializing and injecting them into the component .
* Creating and exposing all required network endpoints.
* Deploying any required platform components (e.g. cloud bridge, ROS master).

A deployment request is handled asynchronously and the current progress can be retrieved via the REST API endpoints or the rapyuta.io console UI. The
deployment is considered complete only when all the underlying components and dependencies are deployed successfully.

== Shared seployment
In some packages, certain plans may support deployment in a shared configuration. A particular deployment may be a dependency for multiple other
deployments that consume its data and services. This is indicated by the *_shared_* attribute of a plan being set to `True`. For more details,
visit the link:packages.html[packages] section.

.*Example*
[NOTE]
Imagine that rapyuta.io provides the `robomapper` package, which consists of the `robot_controller` and `map_genetator` components. Your application wants to
use many robots to build a map. In order for them to collaborate they should share the `map_generator`. For this, you could use a plan for the `map_generator`
component that supports the shared mode. All deployments of `robomapper` would then share a common `map_generator` while using independent `robot_controller`.
Additionally, imagine another package `visualizer` which uses the `map_generator` data and a `map_visualizer` interface. This package would also share the
same `map_generator` if it is configured as shared.

== Lifecycle
Each Deployment goes through multiple stages, at a single point it can be either:

* In progress
* Running
* Stopped
* Error