= Deployments

A Deployment is a running instance of a package on the platform. A deployment can be triggered from the rapyuta.io console UI, link:../developer_guide/rapyuta_io_sdk/sdk_docs.html[rapyuta.io SDK], or directly using 
REST API endpoints. While deploying a package, the platform is responsible for:

* Resolving all specified package dependencies for a package. 
* Ensuring availability of all required catalog dependencies and then initializing and injecting them into the component.
* Creating and exposing all required network endpoints.
* Deploying any components needed by the platform (e.g., cloud bridge, ROS master).

The platform handles the deployments requests asynchronously and provides REST API endpoints for retrieving the current deployment progress. The progress can
also be checked from the rapyuta.io console UI. The deployment is considered complete only when all the underlying components and dependencies are deployed
successfully.

== Singleton Deployment
In some packages, certain plans may support deployment in a Singleton configuration. A particular deployment may be a dependency for multiple other deployments that consume its data and services. This is indicated by the *_singeleton_* attribute of a plan being set to `True`. Please refer to the design patterns section of the link:service_catalog.html[service catalog] docs for a overview.



== Lifecycle
Each Deployment goes through multiple stages, at a single point it can be either:

* In progress
* Running
* Stopped
* Error

[TIP]
To learn how to deploy packages, visit link:../getting_started/deploying_package.html[this page].