= Resources, users, and groups

== Resources
Resources refer to entities that can be managed by the platform. These can be devices which are already integrated into the platform, packages which are
added to the platform, deployments, and builds. Resources can also be scoped by a user or group.

== Users
In rapyuta.io the user entity responsible for creating and managing resources on the platform (e.g., device, package, deployment). The platform authorization
service is then responsible for granting access to the set of resources available to each authenticated user.

== Groups
Groups are useful when teams want to collaborate or manage a particular set of resources. In rapyuta.io a group facilitates sharing resources (devices,
packages, deployments, etc.)  among an arbitrary number of users. A user can belong to zero or more groups. Any user can create a group from the rapyuta.io
console UI and add or remove users and resources in that group.

.*Example*
[NOTE]
An organization `Rapyuta` has two teams. `Team1` works on drones and `Team2` works on droids. Each team can make a group dedicated to their team members.
Each team member will only be able to access devices (or other resources) added to their group. If an engineer works with both teams, he/she can be added
to both the groups.

[TIP]
Try creating users and groups. Learn how link:../getting_started/creating_users_groups.html[here].