= Introduction to rapyuta.io

The Rapyuta.IO is enterprise ready cloud robotics platform to help you with every stage of the product life cycle for your connected machines. 
It consists of a number of components and services that help you design, build, deploy manage and debug complex distributed robotics applications. 
For example:  Install a ROS Application, build and deploy it across the cloud and device. Then collect logs and monitor your application and services 

== Key features
The rapyuta.io platform strives to provide the right set of tools to solve key problems associated with developing and managing connected machines in an enterprise scenario.


=== Unified "On-Demand" Compute Environment

rapyuta.io provides a fully managed compute environment to run your application seamlessly on the cloud and device. 
Out of the box, the platform abstracts out the complexity associated with managing connected machines so you can concentrate of building the best experience for your client.

rapyuta.io provides:

* Abstract away the data-center or cloud with the rapyuta.io platform featuring built in scalablity, fault-tolerance and resiliency. 
* Spin up compute resources and high-intensity network links only when you need to.
* Declarative manifests to consume platform services and resources in a repeatable way both on device and cloud.
* Logging and Metric pipelines to help you draw insight into your application when it runs on the platform
* Dedicated communication channel to the device featuring:
** App- layer white listing select exactly what information flows over the weak WAN link.
** Tunable for configuring bounds on delays, qos, ttl per topic.
** Randomized endpoints and enterprise grade 2048 bit ssl encryption.
** Over the wire optimization, connection pooling and compression.
** Automated ROS schema and meta-data discovery.

=== IO Catalog and Build Service

Building a new application for your end user does not mean reinventing the wheel and writing every tiny component all over again. 
Additionally it often encumbers the developer with e responsibility of building and releasing the code 
The platform provides a catalog of building blocks you can use to compose your applications. Possible use-cases include but are not limited to 

* Basic components for command channel connectivity to a web browser or a video gateway 
* Services for storing and processing large amount of binary, log or video data
* Enabling algorithms and services: develop in-house or acquire machine learning, computer vision, motion planning algorithms

The Build Engine converts your application source (ROS, Python, JavaScript, Ruby, etc.) into runnable configuration and images for rapyuta.io.

=== Device Management

Tools and utilities in the platform that allow you to manage a heterogeneous set of robots at client sites and remote locations.

A few key features are:

* "Always-On" encrypted communication to and from the device, even behind a firewall!
* Dedicated control and configuration management plane to manage and update your device.
* Dedicated telemetry channel with dedicated infrastructure to collect vital log and metric data at all times.
* Full featured remote terminal and quick debug utilities right from your web browser.
* Flexible fleet management with labels and selectors.
* Rich configurable dashboards and visualizations for collected log/metric data.