= Introduction to rapyuta.io

The rapyuta.io is an enterprise-ready cloud robotics platform to help you with every stage of the software development lifecycle (SDLC) for your connected machines. It consists of a number of components and services that help you design, implement, provision, deploy, operate and debug complex distributed robotics applications.


== Key features
The rapyuta.io platform provides multiple features to help you solve key problems associated with developing and managing connected machines in an enterprise scenario.

=== Application Runtime
The rapyuta.io platform abstracts away the many complexities associated with managing heterogeneous connected machines, eg: multiple software runtimes & architectures, package definitions & dependency graphs, communication channels, security measures, etc. The platform provides a set of constructs so you as the developer can focus on building the best application for your client.

The platform aides the developer by providing:

* Unified way to declare rapyuta.io compatible software packages that span across the cloud and device. 
* Tools and API to deploy these packages in a deterministic repeatable manner 
* An abstraction over data-center or cloud infrastructure with built-in scalability, fault-tolerance, and resiliency.
* Elastic on-demand and compute resources and high-intensity network links to meet changing customer demands
* Logging and Metric pipelines to help you draw insights into your application when it runs on the platform
* A bridge across multiple ROS environments in the cloud and on the device for ROS-native constructs like actions, services, and topics. Features of this bridge include:
** Application layer whitelisting to select exactly what information flows over the weak WAN link.
** Tunables for configuring bounds on delays, QoS, TTL per topic.
** Randomized endpoints and enterprise-grade 2048-bit SSL encryption.
** Over the wire optimization, connection pooling, ordering, and compression.
** Automated ROS message schema detection and metadata discovery.

=== Service Catalog 
The service catalog is a curated collection of public and private applications and services. The Catalog facilitates the design, implementation, and provisioning stages of complex robotic applications by providing discovery, application composability, and dynamic provisioning. The public services provided by the platform can be used as "building blocks" to accelerate the development of your new applications. A possible list of such services could be:

* A video gateway (Eg. Janus)
* ROS Navigation stack (http://wiki.ros.org/navigation)
* ROSBridge suite (http://wiki.ros.org/rosbridge_suite)
     
The Service Catalog can also be used to add private applications for in-house development and use.

=== Device Management

Developers and operators often face logistical and monetary challenges in managing a heterogeneous set of robots at client sites or remote locations.
The platform’s device management layer provides the following features:


* "Always-On" encrypted communication to and from the device, even behind a firewall.
* Dedicated control and configuration management plane to manage and update your device.
* Dedicated telemetry channel with dedicated infrastructure to collect vital log and metric data at all times.
* Full featured remote terminal and quick debug utilities right from your web browser.
* Flexible fleet management using a query DSL based on telemetry data and tags.
* Rich configurable dashboards and visualizations for collected log/metric data.