= Introduction to rapyuta.io

Building a cloud robotics application requires the following elements:

1. *Robot hardware* which again consists of actuators, sensors, computation, and middleware.
2. *Cloud Computing Infrastructure* which allows the robots to offload computation, store and share information, and collaborate with one another.
3. *IoT sensors* to augment the onboard sensors to give the application and robots a better understanding of the surrounding environment.
4. *Enabling algorithms* e.g. motion planning, machine vision, and sensor fusion algorithms that enhance the autonomy of the system.
5. *Field services*, region-wide network of service professionals to install and operate robot hardware.
6. *Business logic*, precise knowledge on the current business process and the end user pain points.

Putting together the above elements requires the infrastructure to:

1. Build, deploy, and provision code on the cloud computing infrastructure and heterogeneous devices.
2. Select and manage the robot/device (software configuration, health management).
3. Select Infrastructure-as-a-Service provider (AWS, Google), private cloud (OpenStack) or bare metal and manage it.
4. Transport data between robots, IoT devices, and the cloud computing infrastructure.
5. Scalable logging and metrics infrastructure for long-term operation.
6. Share and consume 3rd party services.
7. Robot domain-specific storage for learning and sharing knowledge between robots/devices.

rapyuta.io facilitates the interaction of the elements required for building robotics application by providing a set of services and tools. The main
components are device management, unified ROS environment and messaging, build engine, service catalog, and logging services.


== Device management

The Device management service provides the control-plane and a minimal data-plane communication between the device and the platform.

==== Key features

* Deploying and running software components on the device and managing their lifecycle.
* Browser-based SSH access with full-featured TTY to the device, even behind a firewall with no VPN.


== Unified ROS environment and messaging

ROS developers can connect and unify remote ROS environments with a dedicated messaging layer built for ROS that provides a low-latency high-throughput
data-plane over the public internet.

==== Key features

* Prioritize specific data streams.
* Tunables to set bounds on latency and order per topic/service.
* Encryption.
* Handle transient network failure.
* ROS-message transparent with full ROS debug tool compatibility.
* Optional wire compression typically useful for sparse data like maps/point clouds.


== Build engine

The build engine converts your application source into runnable rapyuta.io package artifacts and configurations.

==== Key features

* Pre-canned recipes for converting popular application types (including ROS) into Docker images.
* Share and distribute application recipes for new application types via the catalog.
* Automatic security updates for your application through pre-canned recipes available on rapyuta.io.


== Service catalog

The service catalog is a curated collection of public and private services and robots/devices (as-a-Service) designed by experts. The catalog facilitates
the design, implementation, and provisioning stages of complex robotic applications by providing service discovery, application composition, and dynamic
provisioning.

==== Key features

* Support for adding ROS and non-ROS services as private/public packages
* Search for pre-canned compatible services and devices to build solutions with
* Dependency management between the various rapyuta.io packages and services


== Logging and metric services

rapyuta.io provides a secure, scalable streaming pipeline to collect and visualize data common to cloud robotics applications, e.g., CPU usage, memory
footprint, device status, etc.  The platform also provides a configurable mechanism to collect and introspect data generated by the application via ROS
topics.

==== Key features

* Full-text” search and filtering on log data
* Rich support for time series metrics with adjustable grouping intervals, aggregation (min, max, count, etc.)
* Configurable dashboards for graphs and logs per device or deployment with autorefresh and visual correlation among all sub-plots
* Multiple visualization types (Line graph, bar graph, stacked, single value, etc.)